version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mail-sender
    ports:
      - "8080:8080"
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DATABASE: mailSender
      MONGO_USERNAME: root
      MONGO_PASSWORD: IAmUnsecure!
    restart: always

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: IAmUnsecure!
      MONGO_INITDB_DATABASE: mailSender
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: IAmUnsecure!
      ME_CONFIG_MONGODB_URL: mongodb://root:IAmUnsecure!@mongo:27017/
      ME_CONFIG_BASICAUTH: "false"

