spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: rezerwacje.bialystok3@gmail.com
    password: arqd kyql ouvh qqtk
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
        starttls:
          enable: true
          required: true

  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://root:example@localhost:27017/mails

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
