spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: rezerwacje.bialystok3@gmail.com
    password: arqd kyql ouvh qqtk
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
        starttls:
          enable: true
          required: true

  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DATABASE:mailSender}
      username: ${MONGO_USERNAME:root}
      password: ${MONGO_PASSWORD:IAmUnsecure!}
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
